### ISSUE TITLE
dynamic css

### ISSUE THREAD

**Issue by jantimon** [iheyunfei/pieces-js#2]
does it support dynamic css?

e.g.:

```
css`
  transform: translateX(${x}px);
`
```

**Comment by hyfdev** [comment]
No. I haven't thought it through. But there's a workaround. [dynamic styles](https://github.com/iheyunfei/pieces-js/blob/main/docs/usage.md#dynamic-styles)

```ts
import React from 'react'
import { css } from '@pieces-js/tag'

export function Box({ size }) {
  return (
    <div
      className={css`
        height: var(--box-size);
        width: var(--box-size);
      `}
      style={{ '--box-size': size }}
    />
  )
}
```

The main goal, for now, is to solve the `CSS rules order` problem in atomic CSS-in-JS. You could find more details in this wonderful article [Atomic CSS-in-JS](https://sebastienlorber.com/atomic-css-in-js#css-rules-order).

After solving the order problem, the project will be production-ready and I will be focusing on adding tests.

**Comment by jantimon** [comment]
Dynamic styles are reducing the complexity of js-in-css a lot so it would be great to be build in without hard to maintain workarounds..

Also css-variables won't work in different cases e.g the following does not work:

```
@media (min-width var(--x)) { ... }
```

Afaik the order problem is really hard.

Which atomic styles should the following code generate and in which order?

```css
.foo:nth-child(2n) {
  color: red;
}

.foo:active {
  color: blue;
}

.foo:not(:focus-within) {
  color: orange;
}

@media (min-width 300px) {
  .foo {
    color purple;
  }
}
```

and a second file:

```css

@media (min-width 300px) {
  .bar {
    color purple;
  }
}

.bar:not(:focus-within) {
  color: orange;
}

.bar:active {
  color: blue;
}

.bar:nth-child(2n) {
  color: red;
}
```

**Comment by hyfdev** [comment]
Yeah. I'm going to remove `At-rule` and `pseudo-classes` supports. It creates a lot of edge cases.
It will only support something like 
```ts
const foo = css`
  margin: 0 20px;
  margin-top: 10px;
`
const bar = css`
  margin-top: 10px;
`
```
It first will be transformed to 
```ts
const foo = css`
  margin-top: 0px;
  margin-bottom: 0px; 
  maring-left: 20px;
  maring-right: 20px;
  margin-top: 10px;
`

const bar = css`
  margin-top: 10px;
`
```

and finally
```ts
const foo = css`
  margin-bottom: 0px; 
  maring-left: 20px;
  maring-right: 20px;
  margin-top: 10px;
`

const bar = css`
  margin-top: 10px;
`
```
and compile to
```ts
const foo = 'c1 c2 c3 c4'

const bar = 'c4'
```

This way, no matter what the style order be,
```css
.c1 { margin-bottom: 0px; }
.c2 { margin-left: 20px; }
.c3 { margin-top: 20px; }
.c4 { margin-top: 10px; }
```
and
```css
.c4 { margin-top: 10px; }
.c3 { margin-top: 20px; }
.c2 { margin-left: 20px; }
.c1 { margin-bottom: 0px; }
```
will have a consistent result.

**Comment by hyfdev** [comment]
I haven't figured out how `pseudo-classes` fit into the process. but I guess `At-rule` supports will be removed forever.

**Comment by hyfdev** [comment]
@jantimon You are right that dynamic styles could reduce the complexity. But the approach of pieces-js requires static analysis, code like `transform: translateX(${x}px);` is very hard to do static analysis.

**Comment by jantimon** [comment]
what do you mean by removed?

no os based dark mode?

```
@media (prefers-color-scheme: dark) {
```

no responsiveness?

```
@media (max-width 1200px) {
```

no print?

```
@media print { 
```

no accessibility?

```
@media (prefers-reduced-motion) {
```

no element queries?

```
@container (min-width: 700px){
```

no touch detection?

```
@media (hover: none) and (pointer: coarse) {
```

**Comment by hyfdev** [comment]
Yes. That's the pain in this approach. Nicolas Gallagher has a talk about this. [https://youtu.be/tFFn39lLO-U?t=1184](talk)

**Comment by jantimon** [comment]
oh there is also 

```
@supports (display: grid) {
```

**Comment by jantimon** [comment]
so to summarize its css just with

- limited features for accessibility 
- limited features for browser support
- limited features for responsibility 
- limited code splitting 
- slower build times
- hard to work with dynamic styles 

to me this approach feels like it introduces a lot more problems than it is able to solve

**Comment by hyfdev** [comment]
yeah. But what do you mean about limited code splitting?

**Comment by jantimon** [comment]
let's say you have a special part of your application which is used rarely e.g. only on black friday which ships with special colors, fonts, font sizes and so on... 

your code might look like this:

```js
if (isBlackFriday) {
  import("./blackfriday");
}
if (isVipCustomer) {
  import("./vip");
}
```

this would create 3 chunks but if a specific order must be guaranteed I guess that's not possible anymore as you wouldn't know which css file is load first

this means that all users need to download the black friday and vip css the entire year

**Comment by hyfdev** [comment]
> Yeah. I'm going to remove `At-rule` and `pseudo-classes` supports. It creates a lot of edge cases. It will only support something like
> 
> ```ts
> const foo = css`
>   margin: 0 20px;
>   margin-top: 10px;
> `
> const bar = css`
>   margin-top: 10px;
> `
> ```
> 
> It first will be transformed to
> 
> ```ts
> const foo = css`
>   margin-top: 0px;
>   margin-bottom: 0px; 
>   maring-left: 20px;
>   maring-right: 20px;
>   margin-top: 10px;
> `
> 
> const bar = css`
>   margin-top: 10px;
> `
> ```
> 
> and finally
> 
> ```ts
> const foo = css`
>   margin-bottom: 0px; 
>   maring-left: 20px;
>   maring-right: 20px;
>   margin-top: 10px;
> `
> 
> const bar = css`
>   margin-top: 10px;
> `
> ```
> 
> and compile to
> 
> ```ts
> const foo = 'c1 c2 c3 c4'
> 
> const bar = 'c4'
> ```
> 
> This way, no matter what the style order be,
> 
> ```css
> .c1 { margin-bottom: 0px; }
> .c2 { margin-left: 20px; }
> .c3 { margin-top: 20px; }
> .c4 { margin-top: 10px; }
> ```
> 
> and
> 
> ```css
> .c4 { margin-top: 10px; }
> .c3 { margin-top: 20px; }
> .c2 { margin-left: 20px; }
> .c1 { margin-bottom: 0px; }
> ```
> 
> will have a consistent result.

It doesn't require specific order. The above example shows it.

**Comment by jantimon** [comment]
but pseudo elements need an order 

```css
.b {
  color: orange;
}
.c:hover {
  color:blue
}
.d:focus {
  color:purple
}
```

is not the same as 

```css
.d:focus {
  color:purple
}
.c:hover {
  color:blue
}
.b {
  color: orange;
}
```
